name: CI/CD - Dev

on:
  push:
    branches: [ "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: Restore
        run: dotnet restore ./ReportQueryAPI.sln

      - name: Build
        run: dotnet build ./ReportQueryAPI.sln --configuration Release --no-restore

  analyse:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT }}

  publish:
    runs-on: ubuntu-latest
    needs: analyse
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Set Environment Variables
        run: |
          echo "SQL_DATABASE=${{ secrets.SQL_DATABASE }}" >> $GITHUB_ENV
          echo "SQL_SERVER=${{ secrets.SQL_SERVER }}" >> $GITHUB_ENV
          echo "SQL_USER=${{ secrets.SQL_USER }}" >> $GITHUB_ENV
          echo "SQL_PASSWORD=${{ secrets.SQL_PASSWORD }}" >> $GITHUB_ENV

      - name: Replace Placeholders in appsettings.json
        run: |
          sed -i "s|{SQL_DATABASE}|${SQL_DATABASE}|g" ./ReportQueryAPI/appsettings.json
          sed -i "s|{SQL_SERVER}|${SQL_SERVER}|g" ./ReportQueryAPI/appsettings.json
          sed -i "s|{SQL_USER}|${SQL_USER}|g" ./ReportQueryAPI/appsettings.json
          sed -i "s|{SQL_PASSWORD}|${SQL_PASSWORD}|g" ./ReportQueryAPI/appsettings.json
        
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/reportqueryapi:dev

  scan_docker_image:
    runs-on: ubuntu-latest
    needs: [ publish ]
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2

      - name: Log in to the Container registry 📦
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Scan Docker image 🐳
        uses: snyk/actions/docker@master
        id: docker-image-scan
        continue-on-error: true
        with:
          image: ${{ secrets.DOCKER_USERNAME }}/reportqueryapi:dev
          args: --file=Dockerfile --severity-threshold=medium
          sarif: false
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
